from binarytree import Node

first = Node(1)
first.left = Node(2)
first.right = Node(3)
first.left.left = Node(4)
first.left.right = Node(5)
first.left.left.left = Node(8)
first.left.left.right = Node(9)
first.right.left = Node(6)
first.right.left.left = Node(10)
first.right.left.right = Node(11)
first.right.right = Node(7)
first.right.right.right = Node(12)

second = Node("A")
second.left = Node("B")
second.right = Node("C")
second.right.left = Node("D")
second.right.left.right = Node("E")

third = Node("F")
third.left = Node("G")
third.right = Node("H")
third.right.left = Node("I")
third.right.left.right = Node("J")

fourth = Node(1)
fourth.left = Node(2)
fourth.left.left = Node(4)
fourth.left.left.left = Node(8)
fourth.left.left.right = Node(9)
fourth.left.right = Node(5)
fourth.left.right.left = Node(10)
fourth.left.right.right = Node(11)
fourth.right = Node(3)
fourth.right.right = Node(7)
fourth.right.left = Node(6)
fourth.right.left.left = Node(12)
fourth.right.left.right = Node(13)
fourth.right.right = Node(7)

fifth = Node("A")
fifth.left = Node("B")
fifth.right = Node("C")
fifth.right.right = Node("E")
fifth.right.left = Node("D")

sixth = Node("( )")
sixth.left = Node("( )")
sixth.left.left = Node("( )")
sixth.right = Node("( )")
sixth.right.left = Node("( )")
sixth.right.left.left = Node("( )")
sixth.right.left.right = Node("( )")

seventh = Node("( )")
seventh.left = Node("( )")
seventh.left.left = Node("( )")
seventh.left.right = Node("[ ]")
seventh.left.left.left = Node("[ ]")
seventh.left.left.right = Node("[ ]")
seventh.right = Node("( )")
seventh.right.left = Node("( )")
seventh.right.right = Node("[ ]")
seventh.right.left.left = Node("( )")
seventh.right.left.right = Node("( )")
seventh.right.left.left.right = Node("[ ]")
seventh.right.left.left.left = Node("[ ]")
seventh.right.right = Node("[ ]")
seventh.right.left.right.left = Node("[ ]")
seventh.right.left.right.right = Node("[ ]")

eight = Node(1)
eight.left = Node(2)
eight.left.left = Node(4)
eight.left.left.left = Node(8)
eight.left.left.right = Node(9)
eight.left.right = Node(5)
eight.right = Node(3)
eight.right.left = Node(6)
eight.right.left.left = Node(10)
eight.right.left.right = Node(11)
eight.right.right = Node(7)
eight.right.right.right = Node(12)

nine = Node(1)
nine.left = Node(2)
nine.left.left = Node(4)
nine.left.left.left = Node(8)
nine.left.right = Node(5)
nine.left.left.right = Node(9)
nine.right = Node(3)
nine.right.left = Node(6)
nine.right.left.left = Node(10)
nine.right.left.right = Node(11)
nine.right.right = Node(7)
nine.right.right.right = Node(12)

tenth = Node("Amar")
tenth.left = Node("Janak")
tenth.left.left = Node("Pallav")
tenth.left.left.left = Node("Rudraksh")
tenth.right = Node("Raj")
tenth.right.left = Node("Deepak")
tenth.right.left.left = Node("Ridhiman")
tenth.right.left.right = Node("Tanush")
tenth.right.right = Node("Sanjay")
tenth.right.right.left = Node("Kuvam")
tenth.right.right.right = Node("Kunsh")

print(first)
print(second)
print(third)
print(fifth)
print(fifth)
print(fourth)
print(sixth)
print(seventh)
print(eight)
print(nine)
print(tenth)
